#ifndef TNS_ENTITY_TYPES_H
#define TNS_ENTITY_TYPES_H

#define ENTITY_TYPE_CORGI 0
#define ENTITY_TYPE_CRITTER 1
#define ENTITY_TYPE_NOTE 2
#define ENTITY_TYPE_FLOOR 3
#define ENTITY_TYPE_WALL 4
#define ENTITY_TYPE_HUD 5
#define ENTITY_TYPE_FOREST 6
#define ENTITY_TYPE_MAIN_MENU 7
#define ENTITY_TYPE_CONTROLS_MENU 8
#define ENTITY_TYPE_CHARACTERS_MENU 9
#define ENTITY_TYPE_PAUSE_MENU 10
#define ENTITY_TYPE_TRANSITION 11

// total number of entity types
#define ENTITY_TYPE_MAX 12

#endif